databases:
  - name: tmf-db
    databaseName: tmf_marketplace
    user: tmf_user
    plan: free

services:
  - type: web
    name: tmf-marketplace-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tmf-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "*"
    plan: free
